const cities = {
  "Afghanistan": ["Kabul", "Kandahar", "Herat", "Mazar-e-Sharif", "Kunduz", "Jalalabad", "Taloqan", "Pul-e-Khumri", "Charikar", "Baghlan", "Sheberghan", "Ghazni", "Lashkargah", "Khost", "Mehtarlam", "Balkh", "Farah", "Sar-e-Pul", "Pul-e-Alam", "Aybak", "Firozkoh", "Terinkot", "Spin Boldak", "Maimana", "Gardez", "Bamyan"],
  "Albania": ["Tirana", "Durres", "Vlore", "Shkoder", "Elbasan"],
  "Algeria": ["Algiers", "Oran", "Constantine", "Annaba", "Blida"],
  "Andorra": ["Andorra la Vella", "Escaldes-Engordany", "Encamp", "Sant Julia de Loria"],
  "Angola": ["Luanda", "Huambo", "Lobito", "Benguela", "Lubango"],
  "Antigua and Barbuda": ["Saint John's", "All Saints", "Liberta", "Potter's Village"],
  "Argentina": ["Buenos Aires", "Cordoba", "Rosario", "Mendoza", "La Plata"],
  "Armenia": ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Hrazdan"],
  "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
  "Austria": ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck"],
  "Azerbaijan": ["Baku", "Ganja", "Sumqayit", "Mingachevir", "Shirvan"],
  "Bahamas": ["Nassau", "Freeport", "West End", "Coopers Town"],
  "Bahrain": ["Manama", "Riffa", "Muharraq", "Hamad Town", "A'ali"],
  "Bangladesh": ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet"],
  "Barbados": ["Bridgetown", "Speightstown", "Oistins", "Holetown"],
  "Belarus": ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno"],
  "Belgium": ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liege"],
  "Belize": ["Belize City", "Belmopan", "San Ignacio", "Orange Walk Town"],
  "Benin": ["Cotonou", "Porto-Novo", "Parakou", "Abomey-Calavi", "Djougou"],
  "Bhutan": ["Thimphu", "Phuntsholing", "Punakha", "Paro", "Gelephu"],
  "Bolivia": ["Santa Cruz de la Sierra", "La Paz", "Cochabamba", "Sucre", "Oruro"],
  "Bosnia and Herzegovina": ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar"],
  "Botswana": ["Gaborone", "Francistown", "Molepolole", "Maun", "Serowe"],
  "Brazil": ["Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador", "Fortaleza"],
  "Brunei": ["Bandar Seri Begawan", "Kuala Belait", "Tutong", "Seria"],
  "Bulgaria": ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse"],
  "Burkina Faso": ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Ouahigouya", "Banfora"],
  "Burundi": ["Bujumbura", "Gitega", "Ngozi", "Muyinga", "Rumonge"],
  "Cabo Verde": ["Praia", "Mindelo", "Santa Maria", "Assomada"],
  "Cambodia": ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Poipet"],
  "Cameroon": ["Douala", "Yaounde", "Garoua", "Bamenda", "Bafoussam"],
  "Canada": ["Toronto", "Montreal", "Vancouver", "Calgary", "Ottawa"],
  "Central African Republic": ["Bangui", "Bimbo", "Berberati", "Carnot", "Bambari"],
  "Chad": ["N'Djamena", "Moundou", "Sarh", "Abeche", "Kelo"],
  "Chile": ["Santiago", "Valparaiso", "Concepcion", "Antofagasta", "Vina del Mar"],
  "China": ["Shanghai", "Beijing", "Guangzhou", "Shenzhen", "Chengdu"],
  "Colombia": ["Bogota", "Medellin", "Cali", "Barranquilla", "Cartagena"],
  "Comoros": ["Moroni", "Mutsamudu", "Fomboni", "Domoni"],
  "Congo (Congo-Brazzaville)": ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Owando"],
  "Costa Rica": ["San Jose", "Limon", "Alajuela", "Heredia", "Cartago"],
  "Croatia": ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar"],
  "Cuba": ["Havana", "Santiago de Cuba", "Camaguey", "Holguin", "Santa Clara"],
  "Cyprus": ["Nicosia", "Limassol", "Larnaca", "Paphos", "Famagusta"],
  "Czechia (Czech Republic)": ["Prague", "Brno", "Ostrava", "Plzen", "Liberec"],
  "Côte d'Ivoire": ["Abidjan", "Yamoussoukro", "Bouake", "Daloa", "San-Pedro"],
  "Democratic Republic of the Congo": ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kisangani", "Goma"],
  "Denmark": ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
  "Djibouti": ["Djibouti", "Ali Sabieh", "Tadjoura", "Dikhil"],
  "Dominica": ["Roseau", "Portsmouth", "Marigot", "Berekua"],
  "Dominican Republic": ["Santo Domingo", "Santiago de los Caballeros", "La Romana", "San Pedro de Macoris", "Punta Cana"],
  "Ecuador": ["Guayaquil", "Quito", "Cuenca", "Santo Domingo", "Machala"],
  "Egypt": ["Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Port Said"],
  "El Salvador": ["San Salvador", "Santa Ana", "San Miguel", "Soyapango", "Santa Tecla"],
  "Equatorial Guinea": ["Malabo", "Bata", "Ebebiyin", "Aconibe"],
  "Eritrea": ["Asmara", "Keren", "Massawa", "Assab", "Mendefera"],
  "Estonia": ["Tallinn", "Tartu", "Narva", "Parnu", "Kohtla-Jarve"],
  "Eswatini (Swaziland)": ["Mbabane", "Manzini", "Siteki", "Nhlangano"],
  "Ethiopia": ["Addis Ababa", "Dire Dawa", "Mekelle", "Gondar", "Bahir Dar"],
  "Fiji": ["Suva", "Nadi", "Lautoka", "Labasa", "Ba"],
  "Finland": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu"],
  "France": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice"],
  "Gabon": ["Libreville", "Port-Gentil", "Franceville", "Oyem", "Moanda"],
  "Gambia": ["Banjul", "Serekunda", "Brikama", "Bakau"],
  "Georgia": ["Tbilisi", "Batumi", "Kutaisi", "Rustavi", "Gori"],
  "Germany": ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt"],
  "Ghana": ["Accra", "Kumasi", "Tamale", "Sekondi-Takoradi", "Tema"],
  "Greece": ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa"],
  "Grenada": ["Saint George's", "Grenville", "Gouyave", "Victoria"],
  "Guatemala": ["Guatemala City", "Mixco", "Villa Nueva", "Quetzaltenango", "Escuintla"],
  "Guinea": ["Conakry", "Nzerekore", "Kankan", "Kindia", "Labe"],
  "Guinea-Bissau": ["Bissau", "Bafata", "Gabu", "Cacheu"],
  "Guyana": ["Georgetown", "Linden", "New Amsterdam", "Anna Regina"],
  "Haiti": ["Port-au-Prince", "Cap-Haitien", "Gonaives", "Les Cayes", "Jacmel"],
  "Holy See": ["Vatican City"],
  "Honduras": ["Tegucigalpa", "San Pedro Sula", "La Ceiba", "Choloma", "El Progreso"],
  "Hungary": ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pecs"],
  "Iceland": ["Reykjavik", "Kopavogur", "Hafnarfjordur", "Akureyri"],
  "India": ["Mumbai", "Delhi", "Bengaluru", "Hyderabad", "Chennai"],
  "Indonesia": ["Jakarta", "Surabaya", "Bandung", "Medan", "Bekasi"],
  "Iran": ["Tehran", "Mashhad", "Isfahan", "Karaj", "Shiraz"],
  "Iraq": ["Baghdad", "Basra", "Mosul", "Erbil", "Najaf"],
  "Ireland": ["Dublin", "Cork", "Limerick", "Galway", "Waterford"],
  "Israel": ["Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva"],
  "Italy": ["Rome", "Milan", "Naples", "Turin", "Palermo"],
  "Jamaica": ["Kingston", "Montego Bay", "Spanish Town", "Portmore", "Mandeville"],
  "Japan": ["Tokyo", "Osaka", "Yokohama", "Nagoya", "Sapporo"],
  "Jordan": ["Amman", "Zarqa", "Irbid", "Aqaba", "Salt"],
  "Kazakhstan": ["Almaty", "Astana", "Shymkent", "Karaganda", "Aktobe"],
  "Kenya": ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
  "Kiribati": ["Tarawa", "Betio", "Bikenibeu", "Bairiki"],
  "Kuwait": ["Kuwait City", "Al Ahmadi", "Hawalli", "Salmiya", "Farwaniya"],
  "Kyrgyzstan": ["Bishkek", "Osh", "Jalal-Abad", "Karakol", "Tokmok"],
  "Laos": ["Vientiane", "Savannakhet", "Pakse", "Luang Prabang", "Thakhek"],
  "Latvia": ["Riga", "Daugavpils", "Liepaja", "Jelgava", "Jurmala"],
  "Lebanon": ["Beirut", "Tripoli", "Sidon", "Tyre", "Zahle"],
  "Lesotho": ["Maseru", "Teyateyaneng", "Mafeteng", "Hlotse"],
  "Liberia": ["Monrovia", "Gbarnga", "Buchanan", "Kakata", "Harper"],
  "Libya": ["Tripoli", "Benghazi", "Misrata", "Zawiya", "Sabha"],
  "Liechtenstein": ["Vaduz", "Schaan", "Balzers", "Triesen"],
  "Lithuania": ["Vilnius", "Kaunas", "Klaipeda", "Siauliai", "Panevezys"],
  "Luxembourg": ["Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange"],
  "Madagascar": ["Antananarivo", "Toamasina", "Antsirabe", "Mahajanga", "Fianarantsoa"],
  "Malawi": ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Kasungu"],
  "Malaysia": ["Kuala Lumpur", "George Town", "Johor Bahru", "Ipoh", "Kuching"],
  "Maldives": ["Male", "Addu City", "Fuvahmulah", "Kulhudhuffushi"],
  "Mali": ["Bamako", "Sikasso", "Mopti", "Kayes", "Segou"],
  "Malta": ["Valletta", "Birkirkara", "Sliema", "Mosta", "Qormi"],
  "Marshall Islands": ["Majuro", "Ebeye", "Jabor", "Jaluit"],
  "Mauritania": ["Nouakchott", "Nouadhibou", "Kaedi", "Rosso"],
  "Mauritius": ["Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe", "Quatre Bornes"],
  "Mexico": ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana"],
  "Micronesia": ["Palikir", "Weno", "Kolonia", "Tofol"],
  "Moldova": ["Chisinau", "Tiraspol", "Balti", "Bender", "Cahul"],
  "Monaco": ["Monaco", "Monte Carlo", "La Condamine", "Fontvieille"],
  "Mongolia": ["Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan"],
  "Montenegro": ["Podgorica", "Niksic", "Herceg Novi", "Bar", "Budva"],
  "Morocco": ["Casablanca", "Rabat", "Fes", "Marrakesh", "Tangier"],
  "Mozambique": ["Maputo", "Matola", "Beira", "Nampula", "Chimoio"],
  "Myanmar (Burma)": ["Yangon", "Mandalay", "Naypyidaw", "Bago", "Mawlamyine"],
  "Namibia": ["Windhoek", "Walvis Bay", "Swakopmund", "Rundu", "Oshakati"],
  "Nauru": ["Yaren", "Aiwo", "Meneng", "Denigomodu"],
  "Nepal": ["Kathmandu", "Pokhara", "Lalitpur", "Bharatpur", "Biratnagar"],
  "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
  "New Zealand": ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga"],
  "Nicaragua": ["Managua", "Leon", "Masaya", "Matagalpa", "Chinandega"],
  "Niger": ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua"],
  "Nigeria": ["Lagos", "Kano", "Abuja", "Ibadan", "Port Harcourt"],
  "North Korea": ["Pyongyang", "Hamhung", "Chongjin", "Nampo", "Wonsan"],
  "North Macedonia": ["Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo"],
  "Norway": ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen"],
  "Oman": ["Muscat", "Salalah", "Sohar", "Nizwa", "Sur"],
  "Pakistan": ["Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Gujranwala", "Multan", "Hyderabad", "Peshawar", "Quetta", "Islamabad", "Sargodha", "Sialkot", "Bahawalpur", "Jhang", "Sheikhupura", "Gujrat", "Sukkur", "Larkana", "Sahiwal", "Okara", "Rahim Yar Khan", "Kasur", "Dera Ghazi Khan", "Wah Cantonment", "Mardan", "Nawabshah (Benazirabad)", "Burewala", "Mingora", "Hafizabad", "Chiniot", "Jhelum", "Kamoke", "Khanewal", "Sadiqabad", "Turbat",
               "Mirpur Khas", "Muridke", "Khanpur", "Bahawalnagar", "Kohat", "Muzaffargarh", "Abbottabad", "Mandi Bahauddin", "Daska", "Pakpattan", "Dera Ismail Khan", "Jacobabad", "Chakwal", "Khuzdar", "Gojra", "Vehari", "Shikarpur", "Ahmedpur East", "Hub", "Chishtian", "Khairpur", "Dadu", "Samundri", "Ferozwala", "Attock", "Tando Adam", "Tando Allahyar", "Jaranwala", "Bholari", "Muzaffarabad", "Hasilpur", "Kamalia", "Kot Abdul Malik", "Panjgur", "Arif Wala", "Gujranwala Cantonment", "Swabi", "Jampur", "Jatoi", "Wazirabad", "Layyah",
               "Shujabad", "Haroonabad", "Jalalpur Jattan", "Umerkot", "Lodhran", "Moro", "Kot Addu", "Mian Channu", "Khushab", "Rajanpur", "Mansehra", "Taxila", "Mirpur", "Kabal", "Bhakkar", "Narowal", "Chaman", "Mianwali", "Shakargarh", "Mailsi", "Nowshera", "Dipalpur", "Haveli Lakha", "Lala Musa", "Shahdadkot", "Charsadda", "Ghotki", "Sambrial", "Bhalwal", "Badin", "Taunsa", "Barikot", "Phool Nagar", "Tando Muhammad Khan", "Pattoki", "Shahdadpur", "Jauharabad", "Kamber Ali Khan", "Chichawatni", "Farooqabad", "Pishin", "Dera Murad Jamali", "Kotri", "Sangla Hill", "Gujar Khan", "Kharian",
                "Pasrur", "Shabqadar", "Kot Radha Kishan", "Ludhewala Waraich", "Renala Khurd"],
  "Palau": ["Ngerulmud", "Koror", "Melekeok", "Airai"],
  "Palestine State": ["Gaza City", "Jerusalem", "Hebron", "Nablus", "Ramallah"],
  "Panama": ["Panama City", "San Miguelito", "Colon", "David", "Santiago"],
  "Papua New Guinea": ["Port Moresby", "Lae", "Mount Hagen", "Madang", "Goroka"],
  "Paraguay": ["Asuncion", "Ciudad del Este", "San Lorenzo", "Luque", "Capiata"],
  "Peru": ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Cusco"],
  "Philippines": ["Manila", "Quezon City", "Davao City", "Cebu City", "Zamboanga City"],
  "Poland": ["Warsaw", "Krakow", "Lodz", "Wroclaw", "Poznan"],
  "Portugal": ["Lisbon", "Porto", "Braga", "Coimbra", "Funchal"],
  "Qatar": ["Doha", "Al Rayyan", "Al Wakrah", "Umm Salal", "Al Khor"],
  "Romania": ["Bucharest", "Cluj-Napoca", "Timisoara", "Iasi", "Constanta"],
  "Russia": ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan"],
  "Rwanda": ["Kigali", "Butare", "Gisenyi", "Musanze", "Rubavu"],
  "Saint Kitts and Nevis": ["Basseterre", "Charlestown", "Sandy Point Town"],
  "Saint Lucia": ["Castries", "Vieux Fort", "Gros Islet", "Soufriere"],
  "Saint Vincent and the Grenadines": ["Kingstown", "Georgetown", "Barrouallie", "Port Elizabeth"],
  "Samoa": ["Apia", "Vaitele", "Faleula", "Siusega"],
  "San Marino": ["San Marino", "Serravalle", "Borgo Maggiore", "Domagnano"],
  "Sao Tome and Principe": ["Sao Tome", "Santo Antonio", "Neves", "Trindade"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam"],
  "Senegal": ["Dakar", "Touba", "Thies", "Saint-Louis", "Kaolack"],
  "Serbia": ["Belgrade", "Novi Sad", "Nis", "Kragujevac", "Subotica"],
  "Seychelles": ["Victoria", "Anse Boileau", "Beau Vallon", "Takamaka"],
  "Sierra Leone": ["Freetown", "Bo", "Kenema", "Makeni", "Koidu"],
  "Singapore": ["Singapore"],
  "Slovakia": ["Bratislava", "Kosice", "Presov", "Zilina", "Nitra"],
  "Slovenia": ["Ljubljana", "Maribor", "Celje", "Kranj", "Koper"],
  "Solomon Islands": ["Honiara", "Auki", "Gizo", "Noro"],
  "Somalia": ["Mogadishu", "Hargeisa", "Bosaso", "Kismayo", "Baidoa"],
  "South Africa": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth"],
  "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon"],
  "South Sudan": ["Juba", "Wau", "Malakal", "Yei", "Bor"],
  "Spain": ["Madrid", "Barcelona", "Valencia", "Seville", "Malaga"],
  "Sri Lanka": ["Colombo", "Kandy", "Galle", "Jaffna", "Negombo"],
  "Sudan": ["Khartoum", "Omdurman", "Port Sudan", "Nyala", "Kassala"],
  "Suriname": ["Paramaribo", "Lelydorp", "Nieuw Nickerie", "Moengo"],
  "Sweden": ["Stockholm", "Gothenburg", "Malmo", "Uppsala", "Vasteras"],
  "Switzerland": ["Zurich", "Geneva", "Basel", "Bern", "Lausanne"],
  "Syria": ["Damascus", "Aleppo", "Homs", "Latakia", "Hama"],
  "Tajikistan": ["Dushanbe", "Khujand", "Kulob", "Bokhtar", "Istaravshan"],
  "Tanzania": ["Dar es Salaam", "Dodoma", "Mwanza", "Arusha", "Mbeya"],
  "Thailand": ["Bangkok", "Chiang Mai", "Pattaya", "Phuket", "Nakhon Ratchasima"],
  "Timor-Leste": ["Dili", "Baucau", "Maliana", "Suai"],
  "Togo": ["Lome", "Sokode", "Kara", "Kpalime", "Atakpame"],
  "Tonga": ["Nuku'alofa", "Neiafu", "Pangai", "Haveluloto"],
  "Trinidad and Tobago": ["Port of Spain", "San Fernando", "Chaguanas", "Arima", "Point Fortin"],
  "Tunisia": ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte"],
  "Turkey": ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya"],
  "Turkmenistan": ["Ashgabat", "Turkmenabat", "Dashoguz", "Mary", "Balkanabat"],
  "Tuvalu": ["Funafuti", "Vaiaku", "Asau", "Savave"],
  "Uganda": ["Kampala", "Gulu", "Mbarara", "Jinja", "Mbale"],
  "Ukraine": ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Lviv"],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman"],
  "United Kingdom": ["Bath", "Birmingham", "Bradford", "Brighton & Hove", "Bristol", "Cambridge", "Canterbury", "Carlisle", "Chelmsford", "Chester", "Chichester", "Colchester", "Coventry", "Derby", "Doncaster", "Durham","Ely","Exeter","Gloucester","Hereford","Kingston-upon-Hull","Lancaster","Leeds","Leicester","Lichfield", "Lincoln", "Liverpool", "London", "Manchester","Milton Keynes", "Newcastle-upon-Tyne","Norwich", "Nottingham", "Oxford", "Peterborough", "Plymouth", "Portsmouth", "Preston", "Ripon", "Salford", "Salisbury", "Sheffield", "Southampton", "Southend-on-Sea", "St Albans",
                     "Stoke on Trent", "Sunderland","Truro","Wakefield","Wells","Westminster","Winchester","Wolverhampton","Worcester","York","Armagh","Bangor (Northern Ireland)","Belfast","Lisburn","Londonderry","Newry","Aberdeen","Dundee","Dunfermline","Edinburgh","Glasgow","Inverness",
                     "Perth", "Stirling","Bangor (Wales)","Cardiff","Newport","St Asaph","St Davids","Swansea","Wrexham"],
  "United States of America": ["New York City", "Los Angeles", "Chicago", "Houston", "Phoenix"],
  "Uruguay": ["Montevideo", "Salto", "Ciudad de la Costa", "Paysandu", "Las Piedras"],
  "Uzbekistan": ["Tashkent", "Samarkand", "Namangan", "Andijan", "Bukhara"],
  "Vanuatu": ["Port Vila", "Luganville", "Norsup", "Isangel"],
  "Venezuela": ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay"],
  "Vietnam": ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hai Phong", "Can Tho"],
  "Yemen": ["Sanaa", "Aden", "Taiz", "Al Hudaydah", "Ibb"],
  "Zambia": ["Lusaka", "Kitwe", "Ndola", "Kabwe", "Livingstone"],
  "Zimbabwe": ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru"]
};

export default cities;
